# cd googlecontainer
# mkdir kube-dashboard
# cd kube-dashboard
# vim Dockerfile

FROM gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1
MAINTAINER qiushida@buaa.edu.cn

# cd <克隆代码根目录>
# git add .
# git commit -m "kubernetes-dashboard-amd64:v1.7.1"
# git push
